networks:
  flask-network:
    driver: bridge

services:
  backend:
    networks:
      - flask-network
    image: ryanglug/jenkins-flask:latest
    container_name: flask-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "http://localhost:8000/api"
    image: ryanglug/flask-api-front:latest
    networks:
      - flask-network
    container_name: flask-frontend
    ports:
      - "2000:80"
